spring:
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      show-sql: true
      hibernate:
        ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payments
    topics:
      online: online
      offline: offline