spring:
  profiles.active: default
  application.name: payments

logging:
  pattern:
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.wefox: ${LOG_LEVEL_WEFOX:DEBUG}

---

spring:
  config.activate.on-profile: default

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      show-sql: true
      hibernate:
        ddl-auto: validate
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/payments
    username: tech
    password: test

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: payments
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json:
          trusted.packages: com.wefox.payments.dto
          value.default.type: com.wefox.payments.dto.PaymentDto
    topics:
      online: online
      offline: offline

---

spring:
  config.activate.on-profile: test

